# Generated by Django 3.2.7 on 2022-02-12 17:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(max_length=255, verbose_name='單位')),
                ('city', models.CharField(max_length=255, verbose_name='城市')),
                ('addr', models.CharField(max_length=255, verbose_name='地址')),
                ('md5_address', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Cate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='類別名')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_id', models.CharField(max_length=255, verbose_name='課程代碼')),
                ('name', models.CharField(max_length=255, verbose_name='課程')),
                ('mongo_id', models.CharField(max_length=255)),
                ('summary', models.TextField(verbose_name='內容')),
                ('Price_Ownpay', models.IntegerField(verbose_name='價格')),
                ('Training_Hours', models.IntegerField(verbose_name='時數')),
                ('Training_StartDate', models.DateTimeField(verbose_name='訓練開始日期')),
                ('Training_EndDate', models.DateTimeField(verbose_name='訓練結束日期')),
                ('link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Leng',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='語言')),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('url_name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('menus', models.ManyToManyField(to='iiiedu.Menu')),
            ],
            options={
                'verbose_name_plural': '角色',
            },
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('en', models.CharField(max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('roles', models.ManyToManyField(blank=True, to='iiiedu.Role')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='標籤名')),
                ('cate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iiiedu.cate', verbose_name='類別')),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('en', models.CharField(blank=True, default='', max_length=256)),
                ('theme', models.ManyToManyField(blank=True, to='iiiedu.Theme')),
            ],
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iiiedu.course')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': '留言',
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iiiedu.course')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': '收藏',
            },
        ),
        migrations.AddField(
            model_name='course',
            name='Tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iiiedu.tag', verbose_name='標籤'),
        ),
        migrations.AddField(
            model_name='course',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iiiedu.branch', verbose_name='分校'),
        ),
        migrations.AddField(
            model_name='course',
            name='leng',
            field=models.ManyToManyField(blank=True, to='iiiedu.Leng', verbose_name='語言'),
        ),
        migrations.AddField(
            model_name='course',
            name='series',
            field=models.ManyToManyField(blank=True, to='iiiedu.Series', verbose_name='領域'),
        ),
    ]
